### PR TITLE
Update formula for 0.14.0 release

### PR DESCRIPTION
**Pull request by pierredup**

### CODE REVIEW

**Comment by maks-rafalko** [comment]
Thank you!

Let's wait until https://github.com/infection/infection/issues/795 is fixed

**Comment by maks-rafalko** [comment]
Could you please update it to 0.14.1? Then we can merge it :)

**Comment by pierredup** [comment]
@maks-rafalko Done

**Comment by maks-rafalko** [comment]
Cool, thanks!

Is there any documentation on how to do it? Thinking about automating this stuff.

**Comment by pierredup** [comment]
It doesn't look like infection/infection#476 is working, I'll look at other ways to automate this

**Pull request merged**
